### PR TITLE
Remind to run "yarn" if deps out of date

### PR DESCRIPTION
**Pull request by mattbrictson**
When developing a project, it is easy to forget to run `yarn install` upon switching branches. If the branch has a different set of dependencies in its package.json or yarn.lock file, the app may still boot up, but you will likely run into errors at some point.

This commit adds the `yarn-deps-check` step prior to `yarn start`, which is an extremely fast check (similar to `yarn check --integrity`) to see if you remembered to run `yarn install`. If you forgot, it will print a reminder and abort booting the app.

```
$ yarn start
yarn run v1.10.1
$ yarn-deps-check
/Users/mattb/Code/carbonfive/spraygun-react/node_modules/yarn-deps-check/dist/src/function.js:54
        throw err;
        ^

Error: Dependencies check failed. Please run "yarn" to fix.
    at Object.depsCheck [as default] (/Users/mattb/Code/carbonfive/spraygun-react/node_modules/yarn-deps-check/dist/src/function.js:48:21)
    at Object.<anonymous> (/Users/mattb/Code/carbonfive/spraygun-react/node_modules/yarn-deps-check/dist/src/index.js:7:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mattb/Code/carbonfive/spraygun-react/node_modules/yarn-deps-check/dist/src/bin/depsCheck.js:4:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I chose to use [yarn-deps-check](https://www.npmjs.com/package/yarn-deps-check) (which, admittedly, is very new and obscure) instead of `yarn check --integrity` because the latter has a very unhelpful error message that would probably do more harm than good:

```
$ yarn start
yarn run v1.10.1
$ yarn check --integrity
warning Integrity check: Top level patterns don't match
error Integrity check failed
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### CODE REVIEW

**Comment by dylnclrk** [comment]
This looks great! 

That said, I was wondering if there's a way to avoid adding another dependency (but maybe I should just go with the flow). Perhaps we could use a some shell scripting to check if `yarn check --integrity` is good, and if it's not good, hide their (unhelpful) message, and display our own error message.

For instance, this unreadable one-liner:

```
yarn check --integrity &> /dev/null || (echo "ERROR: Looks like your dependencies are not met. Please install dependencies with `$ yarn install`" && exit 1)
```

What do you think? Do you want me to take a crack at writing something a bit clearer?

**Comment by dylnclrk** [comment]
Also, I can't remember, can you just put a shell script like this in to your yarn scripts in package.json?

Maybe we'd need to put it in to a `bin/pre-start` or something instead.

**Comment by dylnclrk** [comment]
Anyway, I'm gonna approve it as is anyway, I don't want to be fussy about dependencies. I don't think there's a way around it in node/js. And using `yarn-check-dependencies` is certainly a lot easier to understand as a user.

**Comment by mattbrictson** [comment]
> For instance, this unreadable one-liner

I think I like your solution better! The only downside is you see the message flash every time you run `yarn start`, since yarn prints the contents of the script before it runs it. Also the shell scripty stuff probably won't work on Windows.

```
$ yarn start
yarn run v1.10.1
$ yarn check --integrity &> /dev/null || (echo 'ERROR: Looks like your dependencies are not met. Please install dependencies with `$ yarn install`' && exit 1)
$ react-scripts start
```

We could probably solve both issues if we moved it into a `bin/pre-start` script. Is that worth the trouble?

**Comment by mattbrictson** [comment]
@dylnclrk I just pushed a commit to redo this as a `bin/pre-start` script. What do you think?

Output looks like:

```
$ yarn start
yarn run v1.10.1
$ node bin/pre-start

  ERROR: Dependencies are not met. Please run `yarn install`.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dylnclrk** [comment]
so good.

**Comment by mattbrictson** [comment]
Thanks! I'll squash the PR and merge.

**Pull request merged**
